---
- name: install python software properties (apt-add-repository)
  apt: pkg=python-software-properties
- name: "Add the Oracle Java JDK repository"
  apt_repository: repo=ppa:webupd8team/java
- name: "Set Java acceptance"
  shell: sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
- name: "install: oracle-java8-installer"
  apt: pkg=oracle-java8-installer
